/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as ExpeditionsRouteImport } from './routes/expeditions'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as MediaRouteImport } from './routes/media'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as PolarMapRouteImport } from './routes/polar-map'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as StudioRouteImport } from './routes/studio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsRoute = ExpeditionsRouteImport.update({
  id: '/expeditions',
  path: '/expeditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const PolarMapRoute = PolarMapRouteImport.update({
  id: '/polar-map',
  path: '/polar-map',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/expeditions': typeof ExpeditionsRoute
  '/explore': typeof ExploreRoute
  '/knowledge': typeof KnowledgeRoute
  '/media': typeof MediaRoute
  '/outreach': typeof OutreachRoute
  '/polar-map': typeof PolarMapRoute
  '/publications': typeof PublicationsRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/expeditions': typeof ExpeditionsRoute
  '/explore': typeof ExploreRoute
  '/knowledge': typeof KnowledgeRoute
  '/media': typeof MediaRoute
  '/outreach': typeof OutreachRoute
  '/polar-map': typeof PolarMapRoute
  '/publications': typeof PublicationsRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/expeditions': typeof ExpeditionsRoute
  '/explore': typeof ExploreRoute
  '/knowledge': typeof KnowledgeRoute
  '/media': typeof MediaRoute
  '/outreach': typeof OutreachRoute
  '/polar-map': typeof PolarMapRoute
  '/publications': typeof PublicationsRoute
  '/studio': typeof StudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/datasets'
    | '/expeditions'
    | '/explore'
    | '/knowledge'
    | '/media'
    | '/outreach'
    | '/polar-map'
    | '/publications'
    | '/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/datasets'
    | '/expeditions'
    | '/explore'
    | '/knowledge'
    | '/media'
    | '/outreach'
    | '/polar-map'
    | '/publications'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/datasets'
    | '/expeditions'
    | '/explore'
    | '/knowledge'
    | '/media'
    | '/outreach'
    | '/polar-map'
    | '/publications'
    | '/studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DatasetsRoute: typeof DatasetsRoute
  ExpeditionsRoute: typeof ExpeditionsRoute
  ExploreRoute: typeof ExploreRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MediaRoute: typeof MediaRoute
  OutreachRoute: typeof OutreachRoute
  PolarMapRoute: typeof PolarMapRoute
  PublicationsRoute: typeof PublicationsRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions': {
      id: '/expeditions'
      path: '/expeditions'
      fullPath: '/expeditions'
      preLoaderRoute: typeof ExpeditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polar-map': {
      id: '/polar-map'
      path: '/polar-map'
      fullPath: '/polar-map'
      preLoaderRoute: typeof PolarMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DatasetsRoute: DatasetsRoute,
  ExpeditionsRoute: ExpeditionsRoute,
  ExploreRoute: ExploreRoute,
  KnowledgeRoute: KnowledgeRoute,
  MediaRoute: MediaRoute,
  OutreachRoute: OutreachRoute,
  PolarMapRoute: PolarMapRoute,
  PublicationsRoute: PublicationsRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
